// Code generated by cmd/settingsgen from contracts/settings/v1/manifest.json. DO NOT EDIT.
//
// Regenerate with: make settings-bindings
//
// Every key, type, scope and default here comes from the manifest, so a client
// cannot drift from the server's contract by editing a constant. Adding a setting
// is a manifest change plus a regeneration, never a hand-written key.

import Foundation

/// Every setting the contract defines.
public enum SettingKey: String, CaseIterable, Sendable {
    /// Metadata language
    case catalogMetadataLanguage = "catalog.metadata_language"
    /// Download quality
    case downloadsDefaultQuality = "downloads.default_quality"
    /// Keep watched downloads
    case downloadsKeepWatched = "downloads.keep_watched"
    /// Download over Wi-Fi only
    case downloadsWifiOnly = "downloads.wifi_only"
    /// Show audiobooks
    case navShowAudiobooks = "nav.show_audiobooks"
    /// Preferred audio language
    case playbackAudioLanguage = "playback.audio_language"
    /// Auto-play next episode
    case playbackAutoPlayNext = "playback.auto_play_next"
    /// Preview next episode
    case playbackAutoPlayNextPreview = "playback.auto_play_next_preview"
    /// Auto-skip credits
    case playbackAutoSkipCredits = "playback.auto_skip_credits"
    /// Auto-skip intros
    case playbackAutoSkipIntro = "playback.auto_skip_intro"
    /// Auto-skip recaps
    case playbackAutoSkipRecap = "playback.auto_skip_recap"
    /// Maximum bitrate
    case playbackMaxBitrateKbps = "playback.max_bitrate_kbps"
    /// Next up prompt
    case playbackNextUpPromptSeconds = "playback.next_up_prompt_seconds"
    /// Preferred quality
    case playbackPreferredQuality = "playback.preferred_quality"
    /// Show forced subtitles
    case playbackShowForcedSubtitles = "playback.show_forced_subtitles"
    /// Subtitle appearance
    case playbackSubtitleAppearance = "playback.subtitle_appearance"
    /// Preferred subtitle language
    case playbackSubtitleLanguage = "playback.subtitle_language"
    /// Subtitles
    case playbackSubtitleMode = "playback.subtitle_mode"
    /// Audio sync offset
    case playerAudioSyncMs = "player.audio_sync_ms"
    /// Dolby Vision
    case playerDolbyVisionEnabled = "player.dolby_vision_enabled"
    /// Dolby Vision Profile 7 fallback
    case playerDvProfile7Hdr10Fallback = "player.dv_profile7_hdr10_fallback"
    /// HDR
    case playerHdrEnabled = "player.hdr_enabled"
    /// Match content frame rate
    case playerMatchFrameRate = "player.match_frame_rate"
    /// Screen orientation
    case playerOrientationMode = "player.orientation_mode"
    /// Still watching prompt
    case playerPassoutThreshold = "player.passout_threshold"
    /// Picture in picture
    case playerPictureInPictureEnabled = "player.picture_in_picture_enabled"
    /// Playback speed
    case playerPlaybackSpeed = "player.playback_speed"
    /// Rewind on resume
    case playerResumeRewindSeconds = "player.resume_rewind_seconds"
    /// Seek cache
    case playerSeekCacheEnabled = "player.seek_cache_enabled"
    /// Default sleep timer
    case playerSleepTimerDefaultMinutes = "player.sleep_timer_default_minutes"
    /// Subtitle sync offset
    case playerSubtitleSyncMs = "player.subtitle_sync_ms"
    /// Video sizing
    case playerVideoGravity = "player.video_gravity"
    /// Search scope
    case searchMediaScope = "search.media_scope"
    /// Match device caption settings
    case subtitleMatchesDevice = "subtitle.matches_device"
    /// Poster badges
    case uiCardOverlays = "ui.card_overlays"
    /// Custom CSS
    case uiCustomCss = "ui.custom_css"
    /// Custom theme variables
    case uiCustomThemeVars = "ui.custom_theme_vars"
    /// Date format
    case uiDateFormat = "ui.date_format"
    /// Hidden libraries
    case uiDisabledLibraryIds = "ui.disabled_library_ids"
    /// High contrast
    case uiHighContrast = "ui.high_contrast"
    /// Library order
    case uiLibraryOrder = "ui.library_order"
    /// Remembered library view
    case uiLibraryPageState = "ui.library_page_state"
    /// Next up episodes
    case uiNextUpMode = "ui.next_up_mode"
    /// Remember library view
    case uiRememberLibraryPageState = "ui.remember_library_page_state"
    /// Pinned sidebar items
    case uiSidebarPins = "ui.sidebar_pins"
    /// Text size
    case uiTextScale = "ui.text_scale"
    /// Text weight
    case uiTextWeight = "ui.text_weight"
    /// Theme
    case uiTheme = "ui.theme"
    /// Time format
    case uiTimeFormat = "ui.time_format"
}

public extension SettingKey {
    static let revision = 1

    /// Keys the server stores. The rest never leave the device.
    static let remote: [SettingKey] = [
        .catalogMetadataLanguage,
        .playbackAudioLanguage,
        .playbackAutoPlayNext,
        .playbackAutoPlayNextPreview,
        .playbackAutoSkipCredits,
        .playbackAutoSkipIntro,
        .playbackAutoSkipRecap,
        .playbackMaxBitrateKbps,
        .playbackNextUpPromptSeconds,
        .playbackPreferredQuality,
        .playbackShowForcedSubtitles,
        .playbackSubtitleAppearance,
        .playbackSubtitleLanguage,
        .playbackSubtitleMode,
        .playerAudioSyncMs,
        .playerDolbyVisionEnabled,
        .playerDvProfile7Hdr10Fallback,
        .playerHdrEnabled,
        .playerMatchFrameRate,
        .playerOrientationMode,
        .playerPlaybackSpeed,
        .playerSeekCacheEnabled,
        .playerSleepTimerDefaultMinutes,
        .playerSubtitleSyncMs,
        .playerVideoGravity,
        .searchMediaScope,
        .uiCardOverlays,
        .uiCustomCss,
        .uiCustomThemeVars,
        .uiDateFormat,
        .uiDisabledLibraryIds,
        .uiHighContrast,
        .uiLibraryOrder,
        .uiLibraryPageState,
        .uiNextUpMode,
        .uiRememberLibraryPageState,
        .uiSidebarPins,
        .uiTextScale,
        .uiTextWeight,
        .uiTheme,
        .uiTimeFormat,
    ]

    static let clientLocal: [SettingKey] = [
        .downloadsDefaultQuality,
        .downloadsKeepWatched,
        .downloadsWifiOnly,
        .navShowAudiobooks,
        .playerPassoutThreshold,
        .playerPictureInPictureEnabled,
        .playerResumeRewindSeconds,
        .subtitleMatchesDevice,
    ]
}
