#!/usr/bin/env bash
# Blocks new /api/v1 request paths in the Apple app sources.
#
# Every file that still mentions a v1 path has a ceiling in the allowlist.
# The check fails when a file's count rises above its ceiling or when a file
# that is not listed starts to match. Counts that drop below the ceiling pass,
# unless --exact is given.
#
# Usage:
#   scripts/ci/check-no-api-v1.sh                 # check against the allowlist
#   scripts/ci/check-no-api-v1.sh --exact         # also fail when a count drops
#   scripts/ci/check-no-api-v1.sh --print-counts  # print a fresh allowlist
#   options: --root DIR (repository root), --allowlist FILE
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "${here}/../.." && pwd)"
allowlist=""
mode="check"
exact=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --print-counts) mode="print"; shift ;;
    --exact) exact=1; shift ;;
    --root) root="$2"; shift 2 ;;
    --allowlist) allowlist="$2"; shift 2 ;;
    -h|--help) sed -n '2,14s/^# \{0,1\}//p' "$0"; exit 0 ;;
    *) echo "check-no-api-v1: unknown argument: $1" >&2; exit 2 ;;
  esac
done
allowlist="${allowlist:-${root}/scripts/ci/api-v1-allowlist.txt}"

scan_dirs=(iosApp/iosApp iosApp/TopShelf iosApp/NotificationService iosApp/DownloadsActivity iosApp/Tests)
pattern='api/v1|"api", *"v1"|appendingPathComponent\("v1"\)'

cd "$root"
existing=()
for dir in "${scan_dirs[@]}"; do
  [[ -d "$dir" ]] && existing+=("$dir")
done

# One "file:line:match" line per occurrence, so two matches on a line count twice.
matches=""
if [[ ${#existing[@]} -gt 0 ]]; then
  matches="$(grep -rnoIE "$pattern" "${existing[@]}" || true)"
fi

counts="$(printf '%s\n' "$matches" | awk -F: 'NF >= 3 { n[$1]++ } END { for (f in n) printf "%s\t%d\n", f, n[f] }' | LC_ALL=C sort)"

if [[ "$mode" == "print" ]]; then
  echo "# Ceiling of /api/v1 path matches per file. Generated by:"
  echo "#   scripts/ci/check-no-api-v1.sh --print-counts > scripts/ci/api-v1-allowlist.txt"
  echo "# Format: <path><TAB><count>. Lines starting with # are ignored."
  [[ -n "$counts" ]] && printf '%s\n' "$counts"
  exit 0
fi

if [[ ! -f "$allowlist" ]]; then
  echo "check-no-api-v1: allowlist not found: $allowlist" >&2
  exit 2
fi

report="$(
  printf '%s\n' "$counts" | awk -F'\t' -v exact="$exact" '
    FNR == NR {
      if ($0 ~ /^#/ || NF < 2) next
      allowed[$1] = $2 + 0
      next
    }
    NF >= 2 {
      seen[$1] = 1
      if (!($1 in allowed)) {
        printf "NEW\t%s\t%d\t0\n", $1, $2
      } else if ($2 + 0 > allowed[$1]) {
        printf "OVER\t%s\t%d\t%d\n", $1, $2, allowed[$1]
      } else if (exact && $2 + 0 < allowed[$1]) {
        printf "UNDER\t%s\t%d\t%d\n", $1, $2, allowed[$1]
      }
    }
    END {
      if (exact) for (f in allowed) if (!(f in seen)) printf "UNDER\t%s\t0\t%d\n", f, allowed[f]
    }
  ' "$allowlist" -
)"

if [[ -z "$report" ]]; then
  echo "check-no-api-v1: ok"
  exit 0
fi

while IFS=$'\t' read -r kind file count allowed; do
  case "$kind" in
    NEW)
      echo "error: ${file} has ${count} /api/v1 path match(es) and is not in the allowlist." ;;
    OVER)
      echo "error: ${file} has ${count} /api/v1 path match(es); the allowlist permits ${allowed}." ;;
    UNDER)
      echo "error: ${file} has ${count} /api/v1 path match(es); the allowlist still records ${allowed}." ;;
  esac
  if [[ "$kind" != "UNDER" ]]; then
    grep -nE "$pattern" "$file" | sed "s|^|  ${file}:|"
  fi
done <<< "$report"

cat <<'EOF'

New code must call /api/v2. To record a deliberate exception, or to lower the
ceilings after removing v1 paths, regenerate the allowlist and commit it:
  scripts/ci/check-no-api-v1.sh --print-counts > scripts/ci/api-v1-allowlist.txt
EOF
exit 1
